version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: suraksha_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: my_database
    ports:
      - "5433:5432"
